<Project>
    <PropertyGroup>
        <CsprojName>$([System.IO.Path]::GetFileNameWithoutExtension($(MSBuildProjectFile)))</CsprojName>
        <RootNamespace>Dev.JoshBrunton.DotnetManageSecrets.$(CsprojName)</RootNamespace>

        <Version>0.9.1</Version>
        <Deterministic>true</Deterministic>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    </PropertyGroup>
</Project>
